runtime: python27
api_version: 1
threadsafe: true
entrypoint: gunicorn -b :$PORT main:app

handlers:
- url: /static
  static_dir: static
- url: /.*
  script: main.app
  
libraries:
  - name: ssl
    version: latest
skip_files:
  
  

